drop table user if EXISTS;
CREATE table user(
  id bigint generated by default as IDENTITY ,
  username VARCHAR (40) ,
  name VARCHAR (20),
  age INT(3) ,
  balance decimal(10,2),
  primary key(id)
);